### ISSUE TITLE
'make' error while compiling

### ISSUE THREAD

**Issue by ashuein** [hwxu/pcma#1]
Error:
Following error takes place while following the steps as mentioned.
>> make

`>> g++ -O3 -Wall -fopenmp ./src/detect_partial_communities.cpp ./src/adjacency_list.cpp -o detect
./src/detect_partial_communities.cpp: In function ‘std::unique_ptr<double []> find_communities(std::unique_ptr<AdjacencyList>&, unsigned int, unsigned int)’:
./src/detect_partial_communities.cpp:166:21: error: ‘fabs’ was not declared in this scope
                 if (fabs(k[0][i] - k_new[0][i]) > EPSILON)
                     ^~~~
./src/detect_partial_communities.cpp:166:21: note: suggested alternative: ‘labs’
                 if (fabs(k[0][i] - k_new[0][i]) > EPSILON)
                     ^~~~
                     labs
./src/detect_partial_communities.cpp:196:41: error: ‘log’ was not declared in this scope
                     if (i < j) log_p += log(d) * 2;
                                         ^~~
./src/detect_partial_communities.cpp:196:41: note: suggested alternative: ‘long’
                     if (i < j) log_p += log(d) * 2;
                                         ^~~
                                         long
./src/detect_partial_communities.cpp:197:35: error: ‘log’ was not declared in this scope
                     else log_p += log(d);
                                   ^~~
./src/detect_partial_communities.cpp:197:35: note: suggested alternative: ‘long’
                     else log_p += log(d);
                                   ^~~
                                   long
Makefile:8: recipe for target 'detect' failed
make: *** [detect] Error 1
`

This error is coming because the math library has not been included in the "detect_partial_communities.cpp" code.

By including #include <math.h> at the top the error is resolved. KIndly update your code.

**Comment by hwxu** [comment]
Thanks for reporting the issue. It seems to be compiler dependent. To comply with C++ style, \<cmath\> is added.
